project:
  type: website
  output-dir: docs
  
website:
  title: "Nora Fried Lab Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - other_stuff.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/Nora-Fried/Nora_Fried_Oct22_Lab_website
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Nora Fried"

format:
  html:
    theme: cosmo
    toc: true

editor: source

